# R Fundies

## Data Types

### Numeric

In [ ]:
5
5.3
-12
# All numeric

[1] 5

[1] 5.3

[1] -12

### Character

In [2]:
'character'
"character"

[1] "character"

[1] "character"

### Logicals

In [5]:
TRUE
FALSE
"They are just boolean values, all caps"
class(FALSE)

[1] TRUE

[1] FALSE

[1] "They are just boolean values, all caps"

[1] "logical"

### Scalars

#### Major Scalar Types

##### Numeric

In [12]:
# Generally floats
a = 3.2;b = 3
a;b
class(b)

[1] 3.2

[1] 3

[1] "numeric"

##### Integer

Apparently not very useful, except for in "extreme edge cases"

In [11]:
c = as.integer(b)
c
class(c)

[1] 3

[1] "integer"

##### Logical

In [7]:
d = TRUE
d

e = as.numeric(d)
e

[1] TRUE

[1] 1

### Vectors

Created with a `c()`

In [13]:
c(1, 2, 3, 4)

[1] 1 2 3 4

In [14]:
c("1", "2", "3", "4")

[1] "1" "2" "3" "4"

In [17]:
c(1, "help", 2)  # these will all be strings

[1] "1"    "help" "2"

`rep` repeats a value

`seq` creates a sequence of some length.

In [18]:
c(rep(4, times=12), rep(20, times=3))

[1]  4  4  4  4  4  4  4  4  4  4  4  4 20 20 20

In [21]:
seq(0, 100, by=5)  # it's inclusive on both sides
seq(1, 3)

[1]   0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
[20]  95 100

[1] 1 2 3

`vector()` gives you a vector of a certain length and certain type with placeholder values. Default value is `0` or an empty string

In [27]:
vector(mode='numeric', length=12)
vector(mode='character', length=12)
vector(mode='logical', length=12)
vector(mode='integer', length=12)

[1] 0 0 0 0 0 0 0 0 0 0 0 0

[1] "" "" "" "" "" "" "" "" "" "" "" ""

[1] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE

[1] 0 0 0 0 0 0 0 0 0 0 0 0

In [35]:
seq(0, 1, length.out=20)  # this will load values in equally spaced increments

seq(1, 5, length.out=5)
seq(0, 5, length.out=5)

[1] 0.00000000 0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 [7] 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
[13] 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
[19] 0.94736842 1.00000000

[1] 1 2 3 4 5

[1] 0.00 1.25 2.50 3.75 5.00

In [32]:
seq(0, 1, by=.1)

[1] 0.0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.0

### Arrays (2-Dimensional Data/Matrices)

In [62]:
arr = array(seq(1, 20), dim=c(4,5))
arr  # stored as a matrix: 4 × 5 of type int

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 2    6    10   14   18  
[3,] 3    7    11   15   19  
[4,] 4    8    12   16   20

In [ ]:
arr[4,2]  # 4th item in the second col
arr[1,]   # first row
arr[,1]   # first col
arr[c(1,3), c(4,5)]  # returns a matrix of the intersection at provided "coords"
# first and third row in colmns 4 and 5
arr[1:3, 3:4]  # returns a matrix of rows 1-3 in cols 3 and 4

[1] 8

[1]  1  5  9 13 17

[1] 1 2 3 4

[,1] [,2]
[1,] 13   17  
[2,] 15   19

[,1] [,2]
[1,]  9   13  
[2,] 10   14  
[3,] 11   15

In [ ]:
arr[-2,]  # all rows but the second
arr[,-3]  # all cols but the third
arr[-1, -2]  # removes first row and second col

[,1] [,2] [,3] [,4] [,5]
[1,] 1    5     9   13   17  
[2,] 3    7    11   15   19  
[3,] 4    8    12   16   20

[,1] [,2] [,3] [,4]
[1,] 1    5    13   17  
[2,] 2    6    14   18  
[3,] 3    7    15   19  
[4,] 4    8    16   20

[,1] [,2] [,3] [,4]
[1,] 2    10   14   18  
[2,] 3    11   15   19  
[3,] 4    12   16   20

[,1] [,2]
[1,] 1    5   
[2,] 2    6

## Comparison Operators

In [38]:
5 > 4
4 == 4
1 != 2
"x" <= "a"

[1] TRUE

[1] TRUE

[1] TRUE

[1] FALSE

Comparisons with arrays, I mean vectors.

In [59]:
lengths <- c(100, 102, 101, 99, 87)  # <- is basically =, but can be used in functions to deconflict with parameter assignments
lengths >= 90  # comparison ran against all elements

[1]  TRUE  TRUE  TRUE  TRUE FALSE

`any`, `all`, `which`, and `subset`

In [ ]:
any(lengths < 200)     # are any less than 200?
all(lengths > 0)       # are all positive?
which(lengths == 101)  # returns index, starting at 0
which(lengths != 99)   # returns a bunch of integers, apparently

# Works like which(), but you can pull indices from other vectors
heights = c(12, 44, 82, 91, 45)
subset(heights, lengths > 101)  # returns second element, 
                                # or "height of item longer than 101 units"

[1] TRUE

[1] TRUE

[1] 3

[1] 1 2 3 5

[1] 44